const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('aurora', {
  overview: () => ipcRenderer.invoke('git:overview'),
  commitDetail: (hash) => ipcRenderer.invoke('git:commitDetail', hash),
  fileDiff: (hash, filePath) => ipcRenderer.invoke('git:fileDiff', hash, filePath),
  workingDiff: (filePath, staged, untracked) => ipcRenderer.invoke('git:workingDiff', filePath, staged, untracked),
  stage: (paths) => ipcRenderer.invoke('git:stage', paths),
  unstage: (paths) => ipcRenderer.invoke('git:unstage', paths),
  commit: (message) => ipcRenderer.invoke('git:commit', message),
  fetch: () => ipcRenderer.invoke('git:fetch'),
  pull: () => ipcRenderer.invoke('git:pull'),
  push: () => ipcRenderer.invoke('git:push'),
  createBranch: (name) => ipcRenderer.invoke('git:createBranch', name),
  checkout: (name) => ipcRenderer.invoke('git:checkout', name),
  deleteBranch: (name, force) => ipcRenderer.invoke('git:deleteBranch', name, force),
  stash: () => ipcRenderer.invoke('git:stash'),
  stashPop: (index) => ipcRenderer.invoke('git:stashPop', index),
  stashDrop: (index) => ipcRenderer.invoke('git:stashDrop', index),
  checkGit: () => ipcRenderer.invoke('app:checkGit'),
  listAccounts: () => ipcRenderer.invoke('accounts:list'),
  oauthStart: (flavor) => ipcRenderer.invoke('oauth:start', flavor),
  oauthPoll: (session) => ipcRenderer.invoke('oauth:poll', session),
  oauthCancel: () => ipcRenderer.invoke('oauth:cancel'),
  addAccount: (account) => ipcRenderer.invoke('accounts:add', account),
  removeAccount: (host) => ipcRenderer.invoke('accounts:remove', host),
  openExternal: (url) => ipcRenderer.invoke('app:openExternal', url),
  listRepos: () => ipcRenderer.invoke('repos:list'),
  selectRepo: (dir) => ipcRenderer.invoke('repos:select', dir),
  addRepo: () => ipcRenderer.invoke('repos:add'),
  removeRepo: (dir) => ipcRenderer.invoke('repos:remove', dir)
});
